/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_song_player_Player */

#ifndef _Included_com_song_player_Player
#define _Included_com_song_player_Player
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_song_player_Player
 * Method:    printPlayerInfor
 * Signature: (Lcom/song/player/Player;)V
 */
JNIEXPORT void JNICALL Java_com_song_player_Player_printPlayerInfor
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
